print(True and True)
print(False and True)
print(1 == 1 and 2 ==1)
print("test" == "test")
print(1 == 1 or 2 != 1)
print(True and 1 == 1)
print(False and 0 != 0)
print(True or 1 == 1)
print("test" == "testing")
print(1 != 0 and 2 == 1)
print("test" != "testing")
print("test" == 1)
print(not(True and False))
print(not(1 == 1 and 0 != 1))
print(not(10 == 1 or 1000 == 1000))
print(not(1 != 10 or 3 ==4))
print(not("testing" == "testing" and "Luis" == "Bueno"))
print(1 == 1 and (not("testing" == 1 or 1 == 0)))
print("sabroso" == "tocino" and (not(3 == 4 or 3 == 3)))
print(3 == 3 and (not("testing" == "testing" or "Python" == "Divertido")))

print((2 == 2 and 1 != 1) or (4 == 5 or 1 != 2)) 
print(4 != 3 or (not 1 == 1)) 
print(not("rest" == "resting" or 1 == 1) and not 2 != 4) 
print((2 == 3 or "rest" != "resting") or not(2 != 3 and 3 == 2))
print(not(2 == 1 and "rest" == "rest") and 4 != 3)